### ISSUE TITLE
[Android] Allow disabling of tracking

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1378]
- [x] Crashlytics is staying
- [x] If Agreed without sharing usage data or disabled in settings, then screen tracking and all other tracking can be disabled.
- [x] For existing users
  - Toggle in settings should be ON after the update
  - The tracking should be enabled
- [x] Note: app restart is not required to disable/enable analytics.
- [x] Link in settings leads to privacy policy page: https://gnosis-safe.io/privacy/
- [x]  add Crash app button to advanced app settings for the stagings app ( internal build)

Zeplin: 

- https://zpl.io/bAg8nYx
- https://zpl.io/agxKWM1

**Comment by liliya-soroka** [comment]
Verified
app version 2.15.0 - 2592
