### ISSUE TITLE
Kyoto Bugs

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-android#624]
* [x] Should not see "Get started" again after accepting terms #619
* [x] Should not be possible to open safe switcher in empty state #634 
* [x] Toolbar styles wrong in dark mode (back arrow and title color) #612 
* [x] Touch feedback (ripple effect) missing in most places
  * Setting cells
  * Get in touch cells
  * Bottom bar
  * Icon to open safe selection
  * Safe selection cells
* [x] Long press to copy address #632
* [x] Fiat currency cell should have no chevron (is not touchable) - https://github.com/gnosis/safe-android/issues/633
  * Appearance doesn't work ... please remove until implemented #570
* [x] Wrong styles in "Load Safe Multisig" screen" -#637
  * toolbar 
    * background should be white
    * Title should be left aligned
    * Next should be capitalized
    * Should use back arrow instead of `< Back`
  * Link to safe website should be in new line with external link icon
  * Different checkmark icon is used then in the designs
  * Different font is used then in the designs
* [x] ENS input should be separate screen https://zpl.io/2GJKJ8Y #621
  * OK button should be initially disabled in ENS dialog
* [x] QR code error should be shown in QR scan screen (https://zpl.io/bzEg38l)  - #646
* [x] Error state of address input should not have `( ! )` #773
* [x] Address input should have 2 lines (address should be fully displayed) #647
* [x] When I go back from the enter name screen I end up on the Overview screen (balances ...), would expect to go one step back (see the filled address input)
* [x] Touch target to open Safe selector is very small (only icon) [What is this referring to? -- @biafra23 ]
* [x] After removing a Safe the next Safe should be shown if available #659
* [x] Would expect the selection dialog to close after selecting a Safe. #660
* [x] According to designs the toolbar on the overview screen should be higher #771
* [x] Balances loading spinner doesn't disappear on error https://github.com/gnosis/safe/issues/319
* [x] Errors should be more descriptive ... e.g. if it is an error because of no internet it should say so https://github.com/gnosis/safe/issues/319 #697 
* [x] After switching tabs (balances to settings back to balances) all data is gone #772 
* [x] Snackbar should be above bottom bar #742 
* [x] If I try to add a Safe without internet it say "Invalid Safe address" even so it is valid #761

**Comment by elgatovital** [comment]
`Should not be possible to open safe switcher in empty state` - we had a discussion about it last week and I think it was agreed to show switcher even if there were no safes added yet. We can still use the Add Safe button of the dialog. So having it always accessible makes sense.

**Comment by tschubotz** [comment]
It's tough for me to prioritze this ticket with major / minor / trivial as it contains too many items. Are the items in here still relevant? If not, could we close it?

**Comment by biafra23** [comment]
@tschubotz I think we can close this, when we have separate tickets for all issues (or solved the issue already). 

I am going through all unchecked issues ATM and write the ticket number next to it.

**Comment by biafra23** [comment]
>  After switching tabs (balances to settings back to balances) all data is gone

@rmeissner Clarification needed: Is the bug, that data is reloaded when switching tabs (current behaviour)?

**Comment by biafra23** [comment]
>  Balances loading spinner doesn't disappear on error

@rmeissner The current behaviour is that the spinner is not removed, when there is an error (no internet, for example). Should we have an error screen instead?

**Comment by biafra23** [comment]
>  Error state of address input should not have ( ! )

@rmeissner How do I reproduce this bug? Is it still occurring?

**Comment by rmeissner** [comment]
just paste an invalid address. Haven't tested this in a while.

**Comment by tschubotz** [comment]
I'm unable to prioritize this ticket still. @elgatovital 
Do I see correctly that all bugs have been moved into their own ticket? If so, could we close this one?

**Comment by tschubotz** [comment]
As far as I see it, all issues are now fixed or in a separate issue -> Closing this.

cc @liliya-soroka @elgatovital
