### ISSUE TITLE
SafeInfo fetch during Transaction List loading + DTOs

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#814]
**TODOs**
- [x] Remove fetching of `SafeInfo` as it is no longer necessary
- [x] Use `SettingsInfo` object instead of `dataDecoded` for `SettingsChange` (In the list)
- [x] Re-use `TransactionInfo` from details into the list
- [x] Match the structure from the gateway and only do types mapping (for `timestamp` for instance, `Long.toDate()`) 
- ~~[ ] Try reducing the amount of types required by the `RecyclerView`~~ **This will change with v2 of the tx list endpoint anyway**

io.gnosis.data.backend.dto.GateTransaction
io.gnosis.data.models.Transaction

Transaction related models should be placed to io.gnosis.data.models.transaction
Explicitly annotate json attributes

**Is your feature request related to a problem? Please describe.**
After integrating the client gateway, there is no need to fetch the `SafeInfo` at the time of loading the transaction list, as its only purpose was to gather the data to calculate the transaction `status`. This is no longer the case, as the `status` is calculated in the gateway; this request has been rendered unnecessary.

`SettingsInfo` contains parameters fetched from `DataDecoded` using the index in the `abi` which is considered the preferred way. The app uses the parameter name adding a failing point for contracts with parameters with the same name for a different type, for example.

`TransactionInfo` is the same class both in the `Summary` and `Detailed` view of the data. This should be leveraged by the app, to avoid duplication.

~~The recyclerView for the TX list consumes 9 different types. Potentially this can be reduced by adding small decision logic in the viewHolder/viewModel. Having so many types makes the code a bit error prone as there is a lot of duplication for data mapping into view types. Making it hard to identify which type specifically may be causing an issue.~~ **This will change with the tx list v2 anyway**
 
**Describe the solution you'd like**
See above section

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0-1495
